# Use the official Node image as a base image for the frontend
FROM node:14

WORKDIR /usr/src/app/frontend

# Copy only the package.json and package-lock.json files
COPY frontend/package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application files
COPY frontend/ ./

CMD ["npm", "start"]