# Use the official Python image as a base image for the backend
FROM python:3.8

WORKDIR /usr/src/app/backend

# Copy the requirements file first to leverage Docker cache
COPY ./backend/requirements.txt .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application code
COPY ./backend/app.py .

EXPOSE 5000

CMD ["python", "app.py"]
